packaging_format = 2

id = "scribe"
name = "Scribe"
description.en = "Automated audio transcription server"
description.fr = "Serveur de transcription audio"

version = "1.0~ynh1"

maintainers = ["Lapineige"]

[upstream]
license = "AGPL-3.0-or-later"
demo = "https://scribe.cemea.org/"
code = "https://gitlab.cemea.org/mallette/scribe"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "5000M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/scribe"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "string"
    choices = ["fr", "en"]
    default = "fr"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://gitlab.cemea.org/mallette/scribe/-/archive/master/scribe-master.tar.gz"
        sha256 = "7d1e8fe75e559305ae74670468d831c41dc3b7e2489cfbea1f019e37425bdb30"

        # autoupdate.strategy = "latest_github_tag" # Does it work with gitlab ?

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    english.exposed = false
    french.exposed = false
    gunicorn.exposed = false
    dmp_server_port.exposed = false

    [resources.apt]
    packages = "python3-dev, python3-venv, python3, python3-pip"
