#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status "$app-gunicorn" >/dev/null; then
    yunohost service remove "$app-gunicorn"
fi

if ynh_hide_warnings yunohost service status "$app-DMP" >/dev/null; then
    yunohost service remove "$app-DMP"
fi

ynh_config_remove_systemd --service=$app-gunicorn
ynh_config_remove_systemd --service=$app-DMP

ynh_config_remove_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
